# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ninjs-framework}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dayton Nolan}]
  s.date = %q{2011-11-15}
  s.description = %q{ninjs-framework is the JavaScript framework component of the ninjs development framework. ninjs-framework is focus on helping you build extensible modular javascript applications, without using a classical inheritance pattern.}
  s.email = %q{daytonn@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".DS_Store",
    ".bundle/config",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/.DS_Store",
    "lib/ninjs-framework.rb",
    "lib/ninjs-framework/assets/jasmine/jasmine-html.js",
    "lib/ninjs-framework/assets/jasmine/jasmine.css",
    "lib/ninjs-framework/assets/jasmine/jasmine.js",
    "lib/ninjs-framework/assets/jasmine/jasmine_favicon.png",
    "lib/ninjs-framework/core/.core.pdoc.yaml",
    "lib/ninjs-framework/core/.existence.pdoc.yaml",
    "lib/ninjs-framework/core/.extend.pdoc.yaml",
    "lib/ninjs-framework/core/.nin.pdoc.yaml",
    "lib/ninjs-framework/core/application.js",
    "lib/ninjs-framework/core/dom.js",
    "lib/ninjs-framework/core/existence.js",
    "lib/ninjs-framework/core/extend.js",
    "lib/ninjs-framework/core/module.js",
    "lib/ninjs-framework/core/nin.js",
    "lib/ninjs-framework/extensions/jquery.elements.js",
    "lib/ninjs-framework/templates/application.js.erb",
    "lib/ninjs-framework/templates/autoload.js.erb",
    "lib/ninjs-framework/templates/core.js.erb",
    "lib/ninjs-framework/templates/dependency.js.erb",
    "lib/ninjs-framework/templates/jasmine.yml.erb",
    "lib/ninjs-framework/templates/test-index.html.erb",
    "lib/ninjs-framework/utilities/all.js",
    "lib/ninjs-framework/utilities/array.js",
    "lib/ninjs-framework/utilities/cookie.js",
    "lib/ninjs-framework/utilities/css.js",
    "lib/ninjs-framework/utilities/number.js",
    "lib/ninjs-framework/utilities/string.js",
    "spec/fixtures/myapp.js",
    "spec/fixtures/nin.js",
    "spec/fixtures/ninjs.conf",
    "spec/fixtures/test.elements.js",
    "spec/fixtures/test.js",
    "spec/fixtures/test.model.js",
    "spec/fixtures/test.module.js",
    "spec/fixtures/utilities.js",
    "spec/javascripts/application_spec.js",
    "spec/javascripts/array_utility_spec.js",
    "spec/javascripts/existence_spec.js",
    "spec/javascripts/extension_spec.js",
    "spec/javascripts/helpers/SpecHelper.js",
    "spec/javascripts/module_spec.js",
    "spec/javascripts/string_utility_spec.js",
    "spec/javascripts/support/jasmine.yml",
    "spec/javascripts/support/jasmine_config.rb",
    "spec/javascripts/support/jasmine_runner.rb",
    "spec/ninjs_framework_spec.rb",
    "spec/spec_helper.rb",
    "spec/tmp/Rakefile",
    "spec/tmp/application/myapp.js",
    "spec/tmp/application/test.js",
    "spec/tmp/elements/test.elements.js",
    "spec/tmp/lib/nin.js",
    "spec/tmp/lib/utilities.js",
    "spec/tmp/models/test.model.js",
    "spec/tmp/modules/test.module.js",
    "spec/tmp/ninjs.conf",
    "spec/tmp/spec/index.html",
    "spec/tmp/spec/javascripts/application_spec.js",
    "spec/tmp/spec/javascripts/array_utility_spec.js",
    "spec/tmp/spec/javascripts/existence_spec.js",
    "spec/tmp/spec/javascripts/extension_spec.js",
    "spec/tmp/spec/javascripts/module_spec.js",
    "spec/tmp/spec/javascripts/string_utility_spec.js",
    "spec/tmp/spec/javascripts/support/jasmine-html.js",
    "spec/tmp/spec/javascripts/support/jasmine.css",
    "spec/tmp/spec/javascripts/support/jasmine.js",
    "spec/tmp/spec/javascripts/support/jasmine.yml.erb",
    "spec/tmp/spec/javascripts/support/jasmine_config.rb",
    "spec/tmp/spec/javascripts/support/jasmine_favicon.png",
    "spec/tmp/spec/javascripts/support/jasmine_runner.rb"
  ]
  s.homepage = %q{http://github.com/daytonn/ninjs-framework}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{ninjs-framework is a small JavaScript framework for building modular javascript applications}
  s.test_files = [
    "spec/javascripts/support/jasmine_config.rb",
    "spec/javascripts/support/jasmine_runner.rb",
    "spec/ninjs_framework_spec.rb",
    "spec/spec_helper.rb",
    "spec/tmp/spec/javascripts/support/jasmine_config.rb",
    "spec/tmp/spec/javascripts/support/jasmine_runner.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jasmine>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jasmine>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jasmine>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jasmine>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jasmine>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jasmine>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

